#:import dp kivy.metrics.dp
#:import MatplotFigure kivy_matplotlib_widget.uix.graph_widget

<ViewScreen>: # Kivy associe ce layout à la class ViewScreen dans Python
    name: "view"

    ScrollView:
        id: view_scroll_layout
        do_scroll_x: False

        MDBoxLayout:
            id: view_content
            orientation: "vertical"
            padding: dp(20)
            spacing: dp(20)
            size_hint: (1, None)
            height: self.minimum_height
			
			# --- Contenu de la zone 1 (menu déroulant exercices + historique complet) ---
            MDBoxLayout:
                id: zone_1_view_content
                orientation: "vertical"
                #spacing: dp(10)
                size_hint_y: None
                height: self.minimum_height
				
				# --- Titre 1 ---
                MDLabel:
					id: title_1
					text: "[b]Exercice[b]"
					markup: True
					halign: "left"
					font_style: root.font_style_subtitle1
					height: dp(10)
					size_hint: (1, None)
				
				# ---- ESPACE ----
				Widget:
					size_hint_y: None
					height: dp(20)
				
				# --- Contenu pour bouton exercice + icône Settings ---
				MDBoxLayout:
					id: exercice_content_2
					orientation: "horizontal"
					pos_hint: {"center_x": 0.5}
					spacing: dp(15)
					size_hint: (0.9, None)
					height: dp(50)
					
					ExerciseDropdown:

					MDIconButton:
                        id: setting_exercise_button
                        icon: "square-edit-outline"
                        icon_size: root.icon_size
                        md_bg_color: (0.2, 0.6, 1, 1)
                        theme_text_color: "Custom"
                        text_color: "white"
                        pos_hint: {"center_y": 0.5}
                        size_hint: None, None
                        on_release: root.create_exercise_settings(self)
				
				# --- Contenant de l'espace + Button accès à l'historique ---
				MDBoxLayout:
					id: history_content
					orientation: "vertical"
					size_hint: 0.9, None
					pos_hint: {"center_x": 0.5}
					opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
					disabled: False if app.selected_exercise else True 
					height: self.minimum_height if app.selected_exercise else 0
					
					# --- Bouton ---
					MDFlatButton:
						id: full_history_button
						text: "voir l'historique complet"
						theme_text_color: "Custom"
						text_color: (0.2, 0.6, 1, 1)
						font_size: root.font_size_button2
						size_hint:(1, None)
						halign: "right"
						_no_ripple_effect: True
						on_release: root.open_history()
			
			MDBoxLayout:
                orientation: "vertical"
				spacing: dp(10)
				pos_hint: {"center_x": 0.5}
				size_hint: 1, None
				opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
				disabled: False if app.selected_exercise else True 
				height: self.minimum_height if app.selected_exercise else 0 # hauteur 0 si pas d'exercice sélectionné
				
				# --- Sélecteur de période pour le graphique ---
				MDBoxLayout:
					size_hint: None, None
					width: self.minimum_width
					spacing: "10dp"
					padding: (dp(10), dp(0))
					pos_hint: {"center_x": 0.5}
					opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
					disabled: False if app.selected_exercise else True 
					height: "40dp" if app.selected_exercise else 0 # hauteur 0 si pas d'exercice sélectionné
					
					MDRaisedButton:
						text: "7j"
						on_release: app.selected_period = "7d"
						opacity: 1 if app.selected_period == "7d" else 0.5
					
					MDRaisedButton:
						text: "4 semaines"
						on_release: app.selected_period = "4s"
						opacity: 1 if app.selected_period == "4s" else 0.5

					MDRaisedButton:
						text: "1 an"
						on_release: app.selected_period = "1y"
						opacity: 1 if app.selected_period == "1y" else 0.5

					MDRaisedButton:
						text: "All"
						on_release: app.selected_period = "all"
						opacity: 1 if app.selected_period == "all" else 0.5

				# --- Contenant des flèches de navigation pour la période (visible uniquement si une période autre que "all" est sélectionnée) ---
				MDBoxLayout:
					size_hint_y: None
					spacing: "10dp"
					opacity: 0 if app.selected_period=="all" else 1
					disabled: True if app.selected_period=="all" else False
					height: 0 if app.selected_period=="all" else "40dp"		

					MDIconButton:
						icon: "arrow-left-bold-circle-outline"
						theme_text_color: "Custom"
						text_color: "grey"
						on_release: app.time_offset += 1
					
					MDLabel:
						text: root.period_label
						halign: "center"        # ✅ horizontal
						valign: "middle"        # ✅ vertical
						size_hint_x: 1          # ✅ prend toute la place
						text_size: self.size    # ✅ nécessaire pour valign

					MDIconButton:
						icon: "arrow-right-bold-circle-outline"
						theme_text_color: "Custom"
						text_color: "grey"
						on_release: app.time_offset = max(0, app.time_offset - 1)
			
			
			# --- Contenu de la zone 2 (Bilan volume de l'activité choisi) ---
            MDBoxLayout:
                id: zone_2_view_content
                orientation: "vertical"
				spacing: dp(10)
				pos_hint: {"center_x": 0.5}
				size_hint: 1, None
				opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
				disabled: False if app.selected_exercise else True 
				height: self.minimum_height if app.selected_exercise else 0 # hauteur 0 si pas d'exercice sélectionné
				
				# --- Titre 2 ---
                MDLabel:
					id: title_2
					text: "[b]Volume[b]"
					markup: True
					halign: "left"
					font_style: root.font_style_subtitle1
					size_hint: (1, None)
					height: dp(10)		

				# Graphique du volume
				MatplotFigure:
					id: volume_graph_widget
					size_hint: (1, None) 
					height: dp(300)
					
				
			# --- Contenu de la zone 3 (Performances) ---
            MDBoxLayout:
                id: zone_3_view_content
                orientation: "vertical"
				spacing: dp(10)
				pos_hint: {"center_x": 0.5}
				size_hint: (1, None)
				opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
				disabled: False if app.selected_exercise else True 
				height: self.minimum_height if app.selected_exercise else 0 # hauteur 0 si pas d'exercice sélectionné
				
				# --- Titre 3 ---
                MDLabel:
					id: title_3
					text: "[b]Performances[b]"
					markup: True
					halign: "left"
					font_style: root.font_style_subtitle1
					size_hint: (1, None)
					height: dp(10)
				
				# --- Graphique des performances ---
				MatplotFigure:
					id: perf_graph_widget
					size_hint: (1, None)
					height: dp(300)
			
			MDBoxLayout:
				orientation: "vertical"
				size_hint_y: None
				height: "80dp"
				padding: "10dp"

				MDLabel:
					id: selected_date
					text: "Date : -"
					halign: "center"

				MDLabel:
					id: selected_perf
					text: "Perf : -"
					halign: "center"

				MDLabel:
					id: selected_details
					text: ""
					halign: "center"
