#:import dp kivy.metrics.dp
#:import MatplotFigure kivy_matplotlib_widget.uix.graph_widget

<ViewScreen>: # Kivy associe ce layout à la class ViewScreen dans Python
    name: "view"

    ScrollView:
        id: view_scroll_layout
        do_scroll_x: False

        MDBoxLayout:
            id: view_content
            orientation: "vertical"
            padding: dp(20)
            spacing: dp(20)
            size_hint: (1, None)
            height: self.minimum_height
			
			# --- Contenu de la zone 1 (menu déroulant exercices + historique complet) ---
            MDBoxLayout:
                id: zone_1_view_content
                orientation: "vertical"
                #spacing: dp(10)
                size_hint_y: None
                height: self.minimum_height
				
				# --- Titre 1 ---
                MDLabel:
					id: title_1
					text: "[b]Exercice[b]"
					markup: True
					halign: "left"
					font_style: root.font_style_subtitle1
					height: dp(10)
					size_hint: (1, None)
				
				# ---- ESPACE ----
				Widget:
					size_hint_y: None
					height: dp(20)
				
				# --- Contenu pour bouton exercice + icône Settings ---
				MDBoxLayout:
					id: exercice_content_2
					orientation: "horizontal"
					pos_hint: {"center_x": 0.5}
					spacing: dp(15)
					size_hint: (0.9, None)
					height: dp(50)
					
					ExerciseDropdown:

					MDIconButton:
                        id: setting_exercise_button
                        icon: "square-edit-outline"
                        icon_size: root.icon_size
                        md_bg_color: (0.2, 0.6, 1, 1)
                        theme_text_color: "Custom"
                        text_color: "white"
                        pos_hint: {"center_y": 0.5}
                        size_hint: None, None
                        on_release: root.create_exercise_settings(self)
				
				# --- Contenant de l'espace + Button accès à l'historique ---
				MDBoxLayout:
					id: history_content
					orientation: "vertical"
					size_hint: 0.9, None
					pos_hint: {"center_x": 0.5}
					opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
					disabled: False if app.selected_exercise else True 
					height: self.minimum_height if app.selected_exercise else 0
					
					# --- Bouton ---
					MDFlatButton:
						id: full_history_button
						text: "voir l'historique complet"
						theme_text_color: "Custom"
						text_color: (0.2, 0.6, 1, 1)
						font_size: root.font_size_button2
						size_hint:(1, None)
						halign: "right"
						_no_ripple_effect: True
						on_release: root.open_history()
			
			MDBoxLayout:
                orientation: "vertical"
				spacing: dp(10)
				pos_hint: {"center_x": 0.5}
				size_hint: 1, None
				opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
				disabled: False if app.selected_exercise else True 
				height: self.minimum_height if app.selected_exercise else 0 # hauteur 0 si pas d'exercice sélectionné
				
				# --- Sélecteur de période pour le graphique ---
				MDBoxLayout:
					size_hint: None, None
					width: self.minimum_width
					spacing: "10dp"
					padding: (dp(10), dp(0))
					pos_hint: {"center_x": 0.5}
					opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
					disabled: False if app.selected_exercise else True 
					height: "40dp" if app.selected_exercise else 0 # hauteur 0 si pas d'exercice sélectionné
					
					MDRaisedButton:
						text: "7j"
						on_release: app.selected_period = "7d"
						opacity: 1 if app.selected_period == "7d" else 0.5
					
					MDRaisedButton:
						text: "4 semaines"
						on_release: app.selected_period = "4s"
						opacity: 1 if app.selected_period == "4s" else 0.5

					MDRaisedButton:
						text: "1 an"
						on_release: app.selected_period = "1y"
						opacity: 1 if app.selected_period == "1y" else 0.5

					MDRaisedButton:
						text: "All"
						on_release: app.selected_period = "all"
						opacity: 1 if app.selected_period == "all" else 0.5

				# --- Contenant des flèches de navigation pour la période (visible uniquement si une période autre que "all" est sélectionnée) ---
				MDBoxLayout:
					size_hint_y: None
					spacing: "10dp"
					opacity: 0 if app.selected_period=="all" else 1
					disabled: True if app.selected_period=="all" else False
					height: 0 if app.selected_period=="all" else "40dp"		

					MDIconButton:
						icon: "arrow-left-bold-circle-outline"
						theme_text_color: "Custom"
						text_color: "grey"
						on_release: app.time_offset += 1
					
					MDLabel:
						text: root.period_label
						halign: "center"        # ✅ horizontal
						valign: "middle"        # ✅ vertical
						size_hint_x: 1          # ✅ prend toute la place
						text_size: self.size    # ✅ nécessaire pour valign

					MDIconButton:
						icon: "arrow-right-bold-circle-outline"
						theme_text_color: "Custom"
						text_color: "grey"
						on_release: app.time_offset = max(0, app.time_offset - 1)
			
			
			# --- Contenu de la zone 2 (Bilan volume de l'activité choisi) ---
            MDBoxLayout:
                id: zone_2_view_content
                orientation: "vertical"
				spacing: dp(10)
				pos_hint: {"center_x": 0.5}
				size_hint: 1, None
				opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
				disabled: False if app.selected_exercise else True 
				height: self.minimum_height if app.selected_exercise else 0 # hauteur 0 si pas d'exercice sélectionné
				
				# --- Titre 2 ---
                MDLabel:
					id: title_2
					text: "[b]Volume[b]"
					markup: True
					halign: "left"
					font_style: root.font_style_subtitle1
					size_hint: (1, None)
					height: dp(10)		

				# Graphique du volume
				MatplotFigure:
					id: volume_graph_widget
					size_hint: (1, None) 
					height: dp(300)
					
				
			# --- Contenu de la zone 3 (Performances) ---
            MDBoxLayout:
                id: zone_3_view_content
                orientation: "vertical"
				spacing: dp(10)
				pos_hint: {"center_x": 0.5}
				size_hint: (1, None)
				opacity: 1 if app.selected_exercise else 0 # invisible tant que pas de données
				disabled: False if app.selected_exercise else True 
				height: self.minimum_height if app.selected_exercise else 0 # hauteur 0 si pas d'exercice sélectionné
				
				# --- Titre 3 ---
                MDLabel:
					id: title_3
					text: "[b]Performances[b]"
					markup: True
					halign: "left"
					font_style: root.font_style_subtitle1
					size_hint: (1, None)
					height: dp(10)
				
				# --- Graphique des performances ---
				MatplotFigure:
					id: perf_graph_widget
					size_hint: (1, None)
					height: dp(300)

			# --- Encadré des détails de la session sélectionnée ---
			MDCard:
				id: session_card
				orientation: "vertical"
				elevation: 4
				radius: [12]
				padding: dp(10)
				spacing: dp(15)
				size_hint: 1, None
				height: self.minimum_height
				opacity: 1 if app.selected_session else 0
				disabled: False if app.selected_session else True

				MDBoxLayout:
					orientation: "horizontal"
					padding: dp(10)
					height: dp(30)
					size_hint: 1, None

					MDBoxLayout:
						id: row_date
						orientation: "horizontal"
						pos_hint: {"center_y": 0.5}
						spacing: dp(15)
						size_hint: 0.8, None

						MDIcon:
							icon: "calendar"
							font_size: "20sp"

						MDLabel:
							text: root.selected_date
							halign: "left"
							text_color: "gray"
							font_style: root.font_style_subtitle2

					# --- Contenu pour Edit/Delete ---
					MDBoxLayout:
						id: row_icons_buttons
						orientation: "horizontal"
						pos_hint: {"center_y": 0.5}
						spacing: dp(5)
						size_hint: 0.2, None
						adaptive_height: True

						Widget: # pour pousser les icônes à droite
						
						MDIconButton:
							icon: "pencil"
							theme_text_color: "Custom"
							text_color: "skyblue"
							on_release: root.edit_selected_session()

						MDIconButton:
							icon: "delete"
							theme_text_color: "Custom"
							text_color: "red"
							on_release: root.delete_selected_session()
				
				MDBoxLayout:
					id: perf_session_selected
					orientation: "horizontal"
					spacing: dp(10)
					padding: dp(10)
					size_hint: 1, None
					height: dp(30)
					
					# --- Contenu pour rappel Kg soulevé ---
					MDBoxLayout:
						id: row_kg
						orientation: "horizontal"
						pos_hint: {"center_y": 0.5}
						spacing: dp(15)
						size_hint: 0.3, None
						height: self.minimum_height
						
						MDIcon:
							id: kg_icon
							icon: "weight-kilogram"
							theme_text_color: "Custom"
							text_color: "skyblue"
							font_size: "20sp"
						
						MDLabel:
							id: selected_perf
							text: ""
							halign: "left"
							text_color: "gray"
							font_style: root.font_style_subtitle2
					
					# --- Contenu pour rappel répétitions/série ---
					MDBoxLayout:
						id: row_reps
						orientation: "horizontal"
						pos_hint: {"center_y": 0.5}
						spacing: dp(15)
						size_hint: 0.4, None
						
						MDIcon:
							id: reps_icon
							icon: "layers"
							theme_text_color: "Custom"
							text_color: (1, 0.65, 0.2, 1)
							font_size: "20sp"
						
						MDLabel:
							id: selected_details
							text: ""
							halign: "left"
							text_color: "gray"
							font_style: root.font_style_subtitle2
					
					# --- Contenu pour RPE ---
					MDBoxLayout:
						id: row_rpe
						orientation: "horizontal"
						pos_hint: {"center_y": 0.5}
						size_hint: 0.3, None
						
						MDIcon:
							id: rpe_icon
							icon: "emoticon-neutral-outline"
							theme_text_color: "Custom"
							text_color: "gray"
							font_size: "20sp"

				# --- Contenu pour Notes ---
				MDBoxLayout:
					id: row_icons_buttons
					orientation: "horizontal"
					pos_hint: {"center_y": 0.5}
					spacing: dp(15)
					size_hint: 1, None
					height: dp(30)
					
					MDIcon:
						icon: "note-edit-outline"
						theme_text_color: "Custom"
						text_color: "white"
						pos_hint: {"center_y": 0.5}
						font_size: "20sp"

					MDLabel:
						id: selected_notes
						text: "..."
						halign: "left"
						text_color: "gray"
						font_style: root.font_style_subtitle2
									
